acmeconf/acmeconf/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls import url, include
from django.contrib.auth.models import User
from reservations.models import Event, EventReservation
from rest_framework import routers, serializers, viewsets
from rest_framework_nested import routers
from rest_framework.routers import DefaultRouter
from rest_framework.response import Response
from rest_framework_nested.relations import NestedHyperlinkedRelatedField
from rest_framework.serializers import HyperlinkedModelSerializer
from rest_framework_nested.serializers import NestedHyperlinkedModelSerializer
from django.shortcuts import get_object_or_404
from rest_framework_extensions.mixins import NestedViewSetMixin
from rest_framework_extensions.routers import NestedRouterMixin

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('id', 'username', 'email')

class EventSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Event
        fields = ('id', 'name', 'location', 'max_seats', 'available_seats', 'date', 'ticket_price', 'is_open')

# Serializers define the API representation.
class UserReservationSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = EventReservation
        fields = ('id', 'event', 'user')

# ViewSets define the view behavior.
class UserViewSet(NestedViewSetMixin, viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# ViewSets define the view behavior.
class EventViewSet(NestedViewSetMixin, viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer

# ViewSets define the view behavior.
class UserReservationViewSet(NestedViewSetMixin, viewsets.ModelViewSet):
    queryset = EventReservation.objects.all()
    serializer_class = UserReservationSerializer

class NestedDefaultRouter(NestedRouterMixin, DefaultRouter):
    pass

router = NestedDefaultRouter()

events_router = router.register('event_reservations', UserReservationViewSet)
events_router = router.register('users', UserViewSet)
events_router = router.register('events', EventViewSet)

#nested_links
events_router.register(
    'user_reservations', UserReservationViewSet,
    base_name='booking',
    parents_query_lookups=['event'])


urlpatterns = [
    path('reservations/', include('reservations.urls')),
    path('admin/', admin.site.urls),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

acmeconf/reservations/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
import booking


app_name = 'reservations'

urlpatterns = [
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<event_id>[0-9]+)/reservation/$', views.reservation, name='reservation'),
    url(r'^$', views.index, name='index'),
    path('<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
]

acmeconf/reservations/models.py
from django.db import models
import uuid #creates unique istance for the event prenotation
from django.contrib.auth.models import User
from datetime import date


class Event(models.Model):
    name = models.CharField(max_length=200, default='name')
    location = models.CharField(max_length=200, default='location')
    max_seats = models.IntegerField(default=0)
    available_seats = models.IntegerField(default=0)
    date = models.DateTimeField('date published', auto_now=True)
    ticket_price = models.IntegerField(default=0)
    staff_ticket_price = models.IntegerField(default=0)
    available_money = models.IntegerField(default=0)
    is_open = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class EventReservation(models.Model):
    event = models.CharField(max_length=200, default='event')
    user = models.CharField(max_length=200, default='name')

acmeconf/reservations/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import EventReservation
from .models import Event

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'is_staff']
        exclude = ()
        labels = {
            'is_staff': ('Conference Speaker'),
        }
        help_texts = {
            'username': None,
            'is_staff': ('Check it if you are a conference speaker'),
        }

class EventReservationForm(forms.ModelForm):
    name = forms.CharField(label='Name', max_length=100)
    password = forms.CharField(label='Password', max_length=100)

    class Meta:
        model = EventReservation
        fields = ['event']
        exclude = ('event',)

acmeconf/reservations/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.views.generic import View
from .forms import UserForm
from django.http import HttpResponse
from django.template import loader
from .models import Event
from django.views.generic import DetailView
from .forms import EventReservationForm
from django.contrib.auth.models import User
from zeep import Client
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group


def index(request):
    latest_event_list = Event.objects.order_by('-date')[:5]
    template = loader.get_template('reservations/index.html')
    context = {
        'latest_event_list': latest_event_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, event_id):
    return HttpResponse("You're looking at event %s." % event_id)

class UserFormView(View):
    form_class = UserForm
    template_name = 'reservations/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            #istantiates a user from the form, that is added to the user that we will see in the admin panel
            user = form.save(commit=False)

            #cleaned (normalized) databases
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            #save the user in the database
            user.save()

            #returns User object if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('reservation:index')

        return render(request, self.template_name, {'form': form})

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('reservations:index')
    context = {
        "form": form,
    }
    return render(request, 'reservations/register.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('reservations:index')
            else:
                return render(request, 'reservations/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'reservations/login.html', {'error_message': 'Invalid login'})
    return render(request, 'reservations/login.html')

class EventDetailView(generic.DetailView):
    model = Event


@login_required
def reservation(request, event_id):

    #retrieve an event object by id
    original_event = Event.objects.get(id=event_id)

    if original_event.available_seats > 0 and original_event.is_open == True:

        if request.method == 'POST':
            form = EventReservationForm(request.POST)

            if form.is_valid():

                event = form.save()
                event.user = request.user.id
                event.event = original_event.id
                original_event.available_seats = original_event.available_seats - 1

                #establish the connection to the bank server
                client = Client('http://localhost/Banca/server.wsdl')

                #get bank username and password from the validate form
                name = form.cleaned_data['name']
                password = form.cleaned_data['password']

                #send form data to the bank login service
                risposta = client.service.userLogin(name, password)

                if request.user.is_staff == True:
                    original_event.available_money = original_event.available_money + original_event.staff_ticket_price
                    client.service.transferPayment(original_event.staff_ticket_price, 'michele', risposta['userID'])
                else:
                    original_event.available_money = original_event.available_money + original_event.ticket_price
                    client.service.transferPayment(original_event.ticket_price, 'michele', risposta['userID'])

                client.service.userLogout(risposta['userID'])

                original_event.save()
                event.save()
                return render_to_response('reservations/booked.html')

        else:
            form = EventReservationForm()

            if request.user.is_staff == True:
                return render(request, 'reservations/reservation.html', {
                    'form': form,
                    'price': original_event.staff_ticket_price
                })

            else:
                return render(request, 'reservations/reservation.html', {
                    'form': form,
                    'price': original_event.ticket_price
                })
                
    else:
        original_event.is_open = False
        original_event.save()
        return render_to_response('reservations/closed.html')


#testing

acmeconf/reservations/templates/reservations/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}reservations{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'reservations:index' %}"><img src="{% static "ACMEreservation.png" %}" style="max-height: 65px; max-width: 100px;"/></a>
          </div>
        </div>

            <ul class="nav navbar-nav">
                <li class="{% block index %}{% endblock %}"><a href="/reservations"><strong>Home</strong></a></li>
                <li class="{% block register %}{% endblock %}"><a href="{% url 'reservations:register' %}"><strong>Register</strong></a></li>
                <li class="{% block login_user %}{% endblock %}"><a href="{% url 'reservations:login_user' %}"><strong>Login</strong></a></li>
            </ul>
      </div>
    </div>
  </nav>
  <div class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
      <p class="navbar-text pull-left">© 2018 - ACMEConferences</p>
      <a href="chirpterlink" class="navbar-btn btn-info btn pull-right">
      <span class="glyphicon glyphicon-thumbs-up"></span>  Follow ACME on Chirpter</a>
    </div>
  </div>
{% block body %}
{% endblock %}
</body>
</html>

acmeconf/reservations/templates/reservations/booked.html
<!-- to display the form the directory is localhost/reservations/register -->
{% extends 'reservations/base_visitor.html' %}
{% load staticfiles %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">

                    <img src="{% static "eventbooked.jpg" %}" style="max-height: 295px; max-width: 708px;"/>

                    <a href="{% url 'reservations:index' %}" class="navbar-btn btn-danger btn pull-right">Return to Homepage</a>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

acmeconf/reservations/templates/reservations/closed.html
<!-- to display the form the directory is localhost/reservations/register -->
{% extends 'reservations/base_visitor.html' %}
{% load staticfiles %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">

                    <img src="{% static "full.jpg" %}" style="max-height: 295px; max-width: 500px;"/>

                    <a href="{% url 'reservations:index' %}" class="navbar-btn btn-danger btn pull-right">Return to Homepage</a>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

acmeconf/reservations/templates/reservations/event_detail.html
{% extends 'reservations/base_visitor.html' %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1>{{ event.name }}</h1>
                    <p><strong>Name:</strong> {{ event.name }}</p>
                    <p><strong>Location:</strong> {{ event.location }}</p>
                    <p><strong>Max Seats:</strong> {{ event.max_seats }}</p>
                    <p><strong>Available Seats:</strong> {{ event.available_seats }}</p>
                    <p><strong>Audience Ticket Price:</strong> {{ event.ticket_price }}$</p>
                    <p><strong>Staff Ticket Price:</strong> {{ event.staff_ticket_price }}$</p>
                    <p><strong>Date:</strong> {{ event.date }}</p>
                    <a href="/reservations/{{ event.id }}/reservation"> <button class="btn btn-primary">Pay and book now!</button></a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

acmeconf/reservations/templates/reservations/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="event_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

acmeconf/reservations/templates/reservations/index.html
<!-- Loads the path to your static files -->
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'reservations/style.css' %}"/>

<!-- Bootstrap includes -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<!-- Font includes -->
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">

<!-- Jquery includes -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'reservations:index' %}"><img src="{% static "ACMEreservation.png" %}" style="max-height: 65px; max-width: 100px;"/></a>
        </div>
      </div>

          <ul class="nav navbar-nav">
              <li class="{% block index %}{% endblock %}"><a href="/reservations"><strong>Home</strong></a></li>
              <li class="{% block register_active %}{% endblock %}"><a href="{% url 'reservations:register' %}"><strong>Register</strong></a></li>
              <li class="{% block login_user %}{% endblock %}"><a href="{% url 'reservations:login_user' %}"><strong>Login</strong></a></li>
          </ul>
    </div>
  </div>
</nav>


<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if latest_event_list %}
                        <h1><strong>Latest Events List</strong></h1>
                        <ul>
                        {% for event in latest_event_list %}
                            <li><h3><a href="/reservations/{{ event.id }}/">{{ event.name }}</a></h3></li>
                        {% endfor %}
                        </ul>
                    {% else %}
                        <p>No events are available.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

</div>


  <div class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
      <p class="navbar-text pull-left">© 2018 - ACMEConferences</p>
      <a href="chirpterlink" class="navbar-btn btn-info btn pull-right">
      <span class="glyphicon glyphicon-thumbs-up"></span>  Follow ACME on Chirpter</a>
    </div>
  </div>

acmeconf/reservations/templates/reservations/login.html
{% extends 'reservations/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'reservations/style.css' %}"/>
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'reservations:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'reservations:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

acmeconf/reservations/templates/reservations/register.html
<!-- to display the form the directory is localhost/reservations/register -->
{% extends 'reservations/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

acmeconf/reservations/templates/reservations/registration_form.html
<!-- to display the form the directory is localhost/reservations/register -->

{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'reservations/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

acmeconf/reservations/templates/reservations/reservation.html
<!-- to display the form the directory is localhost/reservations/register -->
{% extends 'reservations/base_visitor.html' %}
{% block title %}Event Reservation{% endblock %}
{% block register_active %}active{% endblock %}
{% load staticfiles %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Event Reservation</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                    <img src="{% static "ebank.jpg" %}" style="max-height: 83px; max-width: 200px;"/>
                    <div class="well"><font color="FireBrick"><strong>Please login with your EBank account to pay the ticket via Wire Transfer</strong></font></div>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p><strong>Ticket price: {{ price }}$</strong></p>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">

                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}